//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GTiHub.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Condition
    {
        public int condId { get; set; }
        public string left_paren { get; set; }
        public int sfieldId { get; set; }
        public string @operator { get; set; }
        public string cond_value { get; set; }
        public string right_paren { get; set; }
        public int transformId { get; set; }
    
        public virtual SourceField SourceField { get; set; }
        public virtual Transformation Transformation { get; set; }
    }
}
