//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GTiHub.Models.EntityModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GTiHubEntities : DbContext
    {
        public GTiHubEntities()
            : base("name=GTiHubEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Condition> Conditions { get; set; }
        public virtual DbSet<Map> Maps { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<ProjectMap> ProjectMaps { get; set; }
        public virtual DbSet<ProjectSource> ProjectSources { get; set; }
        public virtual DbSet<ProjectTarget> ProjectTargets { get; set; }
        public virtual DbSet<Rule> Rules { get; set; }
        public virtual DbSet<RuleSourceField> RuleSourceFields { get; set; }
        public virtual DbSet<Source> Sources { get; set; }
        public virtual DbSet<SourceField> SourceFields { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Target> Targets { get; set; }
        public virtual DbSet<TargetField> TargetFields { get; set; }
        public virtual DbSet<Transformation> Transformations { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserProjectSec> UserProjectSecs { get; set; }
    }
}
