//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GTiHub.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectMap
    {
        public int proj_map_Id { get; set; }
        public int projectId { get; set; }
        public int mapId { get; set; }
    
        public virtual Map Map { get; set; }
        public virtual Project Project { get; set; }
    }
}
