//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GTiHub.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectSource
    {
        public int proj_source_Id { get; set; }
        public int projectId { get; set; }
        public int sourceId { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual Source Source { get; set; }
    }
}
