//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GTiHub.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rule()
        {
            this.RuleSourceFields = new HashSet<RuleSourceField>();
        }
    
        public int ruleId { get; set; }
        public int tfieldId { get; set; }
        public int transformId { get; set; }
        public string rule_value { get; set; }
    
        public virtual TargetField TargetField { get; set; }
        public virtual Transformation Transformation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RuleSourceField> RuleSourceFields { get; set; }
    }
}
