//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GTiHub.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RuleSourceField
    {
        public int rulesourceId { get; set; }
        public int ruleId { get; set; }
        public int sfieldId { get; set; }
        public string append { get; set; }
        public string prepend { get; set; }
        public string custom_format { get; set; }
    
        public virtual Rule Rule { get; set; }
        public virtual SourceField SourceField { get; set; }
    }
}
