//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GTiHub.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SourceField
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SourceField()
        {
            this.Conditions = new HashSet<Condition>();
            this.RuleSourceFields = new HashSet<RuleSourceField>();
        }
    
        public int sfieldId { get; set; }
        public string name { get; set; }
        public System.DateTime creation_date { get; set; }
        public string datatype { get; set; }
        public bool active { get; set; }
        public int sequence_num { get; set; }
        public int sourceId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Condition> Conditions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RuleSourceField> RuleSourceFields { get; set; }
        public virtual Source Source { get; set; }
    }
}
