//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GTiHub.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.UserProjectSecs = new HashSet<UserProjectSec>();
        }
    
        public int userId { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public System.DateTime creation_date { get; set; }
        public string title { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string salt { get; set; }
        public string hash { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserProjectSec> UserProjectSecs { get; set; }
    }
}
